from collections.abc import Sequence

import numpy as np
import numpy.typing as npt

class Circuit:
    @staticmethod
    def R(r: float) -> Circuit: ...
    @staticmethod
    def C(c: float) -> Circuit: ...
    @staticmethod
    def L(l: float) -> Circuit: ...
    @staticmethod
    def La(l: float, alpha: float) -> Circuit: ...
    @staticmethod
    def CPE(q: float, alpha: float) -> Circuit: ...
    @staticmethod
    def W(aw: float) -> Circuit: ...
    @staticmethod
    def Wo(z0: float, tau: float) -> Circuit: ...
    @staticmethod
    def Ws(z0: float, tau: float) -> Circuit: ...
    @staticmethod
    def G(rg: float, tg: float) -> Circuit: ...
    @staticmethod
    def Gs(rg: float, tg: float, phi: float) -> Circuit: ...
    @staticmethod
    def K(r: float, tau_k: float) -> Circuit: ...
    @staticmethod
    def Zarc(r: float, tau_k: float, gamma: float) -> Circuit: ...
    @staticmethod
    def TLMQ(r_ion: float, qs: float, gamma: float) -> Circuit: ...
    @staticmethod
    def T(a_coeff: float, b_coeff: float, a_param: float, b_param: float) -> Circuit: ...
    @staticmethod
    def series(elements: Sequence[Circuit]) -> Circuit: ...
    @staticmethod
    def parallel(elements: Sequence[Circuit]) -> Circuit: ...
    def impedance(self, frequencies: Sequence[float]) -> npt.NDArray[np.complex128]: ...
