[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"

[project]
name = "fasteis"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
dependencies = ["numpy>=1.20"]

[tool.maturin]
features = ["pyo3/extension-module"]

[dependency-groups]
dev = [
    "impedance>=1.7.1",
    "pandas>=2.0.3",
    "polars>=1.8.2",
    "pytest>=8.3.5",
    "ruff>=0.15.20",
    "scipy>=1.10",
]
